"""empty message

Revision ID: 07901d15f2e8
Revises: 0488216e1536
Create Date: 2020-10-16 23:59:53.248396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07901d15f2e8'
down_revision = '0488216e1536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radargram', sa.Column('file_name', sa.String(length=5000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radargram', 'file_name')
    # ### end Alembic commands ###
