"""empty message

Revision ID: 27d7ae405c89
Revises: 944ce5d1a405
Create Date: 2020-10-09 22:30:17.124481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27d7ae405c89'
down_revision = '944ce5d1a405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trace', 'sample_of_surface')
    op.drop_column('trace', 'time_collecting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace', sa.Column('time_collecting', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('trace', sa.Column('sample_of_surface', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
