"""empty message

Revision ID: 944ce5d1a405
Revises: 
Create Date: 2020-10-07 21:26:07.494647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944ce5d1a405'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radargram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('stage_between_traces', sa.Float(), nullable=False),
    sa.Column('time_base', sa.Float(), nullable=False),
    sa.Column('traces_count', sa.Integer(), nullable=False),
    sa.Column('samples_count', sa.Integer(), nullable=False),
    sa.Column('distance_between_antennas', sa.Float(), nullable=False),
    sa.Column('default_velocity', sa.Float(), nullable=False),
    sa.Column('GPR_unit', sa.String(length=1000), nullable=False),
    sa.Column('antenna_name', sa.String(length=1000), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radargram_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('X', sa.Float(), nullable=False),
    sa.Column('Y', sa.Float(), nullable=False),
    sa.Column('Z', sa.Float(), nullable=False),
    sa.Column('PK', sa.Float(), nullable=False),
    sa.Column('sample_of_surface', sa.Integer(), nullable=False),
    sa.Column('amplitudes', sa.PickleType(), nullable=False),
    sa.Column('time_collecting', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['radargram_id'], ['radargram.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trace')
    op.drop_table('radargram')
    op.drop_table('project')
    # ### end Alembic commands ###
